### ISSUE TITLE
ERROR to setup dev environment

### ISSUE THREAD

**Issue by harshilparmar** [reactjs/gu.reactjs.org#66]
Did anyone faced this issue 

Here is full error:

ERROR #85923 GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allExampleCode" on type "Query".

If you don't expect "allExampleCode" to exist on the type "Query" it is most likely a typo.
However, if you expect "allExampleCode" to exist there are a couple of solutions to common problems:

    If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
    The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
    You want to optionally use your field "allExampleCode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\pages\index.js:358:5

failed extract queries from components - 0.758s
success write out requires - 0.146s
success write out redirect data - 0.042s
success Build manifest and related icons - 0.123s
success onPostBootstrap - 0.137s
⠀
info bootstrap finished - 12.114 s
⠀
warn code block or inline code language not specified in markdown. applying generic code block
warn unable to find prism language 'sh' for highlighting. applying generic code block
warn unable to find prism language 'jsxon' for highlighting. applying generic code block

ERROR

UNHANDLED REJECTION [
'/C:\hp\gu.reactjs.org\examples\es5-syntax-example',
Error: C:\hp\gu.reactjs.org\public\page-data\C:\hp\gu.reactjs.org\examples\es5-syntax-example contains invalid WIN32 path characters.
at Object.mkdirs (C:\hp\gu.reactjs.org\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
at Object.mkdirs (C:\hp\gu.reactjs.org\node_modules\universalify\index.js:5:67)
at C:\hp\gu.reactjs.org\node_modules\fs-extra\lib\output\index.js:20:11
at C:\hp\gu.reactjs.org\node_modules\universalify\index.js:23:46 {
code: 'EINVAL'
},
{ elapsed: 33635 }
]

Error: [
'/C:\hp\gu.reactjs.org\examples\es5-syntax-example',
Error: C:\hp\gu.reactjs.org\public\page-data\C:\hp\gu.reactjs.org\examples\es5-syntax-example contains invalid WIN32 path characters.

    mkdirs.js:18 Object.mkdirs
    [gu.reactjs.org]/[fs-extra]/lib/mkdirs/mkdirs.js:18:22

    index.js:5 Object.mkdirs
    [gu.reactjs.org]/[universalify]/index.js:5:67

    index.js:20
    [gu.reactjs.org]/[fs-extra]/lib/output/index.js:20:11

    code: 'EINVAL'

    },

    { elapsed: 33635 }

    ]

    index.js:133 process.
    [gu.reactjs.org]/[gatsby-cli]/lib/index.js:133:14

    index.js:155 processEmit [as emit]
    [gu.reactjs.org]/[signal-exit]/index.js:155:32

    promises.js:209 processPromiseRejections
    internal/process/promises.js:209:33

    task_queues.js:98 processTicksAndRejections
    internal/process/task_queues.js:98:32

not finished run queries - 33.795s
not finished Generating image thumbnails - 33.566s

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————320 pages In Progress react-websiteerror Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I also posted this on main repo.Can anyone help!!

**Comment by 3sanket3** [comment]
@harshilparmar I will check and update

**Comment by harshilparmar** [comment]
@3sanket3 have you checked bro?
