### ISSUE TITLE
Translation of "We will introduce components in the next section"

### ISSUE THREAD

**Issue by 3sanket3** [reactjs/gu.reactjs.org#7]
Actually it's translation is "અમે આગામી વિભાગ માં components નો પરિચય આપીશું". But don't you think generally in any guide of Gujarati we write it as "આપણે આગલા  વિભાગમાં componentsથી પરિચિત થઈશું". It also look nice and give feelings of togetherness rather than one instructing to others.

What do you say?

**Comment by ron4ex** [comment]
👍 for _આપણે આગલા વિભાગમાં components થી પરિચિત થઈશું._

**Comment by hardikpthv** [comment]
+1 "આપણે આગલા વિભાગમાં componentsથી પરિચિત થઈશું"

**Comment by 3sanket3** [comment]
Yeah going with "આપણે આગલા વિભાગમાં componentsથી પરિચિત થઈશું". 

Thanks
