### ISSUE TITLE
Revert the translation 'કેમ છો' back to 'Hello World'

### ISSUE THREAD

**Issue by 3sanket3** [reactjs/gu.reactjs.org#8]
We will have to keep 'Hello World' as it is. At many places in documentation, the code from .js file is directly pulled for code snippets in doc. And if the code in .js file tries to print 'Hello World', we will have update the .js file from src folder. Which we think out of translation scope. 

Under this issue we want to revert that ''કેમ છો' translation back to 'Hello World' for the below pages.

- [x] Home Page 
- [x] Hello World
- [x] Introducing JSX

**Comment by ron4ex** [comment]
There weren't any references to કેમ છો in Home Page. Fixed in the other two.

Fixed in #9
